#!/bin/sh
#if [ "$#" -eq 6 ]; then
#    echo "This script requires the path to the PEM file, the IP of the remote machine, the user to login with (ubuntu or ec2-user), and the port to map to on your local machine."
#    echo "ex. aws_ssh ~/.ssh/key.pem bastion ubuntu 65000 10.0.0.122 ls"
#    exit 1
#fi

KEY=$1
BAST=$2
USER=$3
PORT=$4
IP=$5
CMD=$6

#echo "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${BAST} -i ${KEY} -p 22 -NMS ~/.ssh/${PORT} -f -C -L ${PORT}:${IP}:22"
ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${BAST} -i ${KEY} -p 22 -NMS ~/.ssh/${PORT} -f -C -L ${PORT}:${IP}:22

ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ${KEY} ${USER}@localhost -p ${PORT} < "${CMD}"
